name: CI

on:
  push:
    branches:
      - main
  pull_request: ~

jobs:
  cargo_test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '-- --test-threads 1'

      - name: codecov.io
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  build_release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
